### ISSUE TITLE
JavaScript Interview Contribution

### ISSUE THREAD

**Issue by AbhisekhNayek** [Soumya-0x000/JS-interview-Questions#2]
hi @Soumya-0x000 . I'm actually looking to contribute to new projects or repository. I'm learning JavaScript currently. So i would like to contribute on this repository, if you like. This would be a great start for me. Also looked onto your README.

Can i contribute ? ...

Thank you 😊

**Comment by Soumya-0x000** [comment]
Yes! Of course..........
It would be a great pleasure to me. 😊
