### ISSUE TITLE
LeetCode 30 Days Problem Contribution

### ISSUE THREAD

**Issue by AbhisekhNayek** [Soumya-0x000/JS-interview-Questions#4]
Hi @Soumya-0x000,

I'm currently diving deep into JavaScript and I'm eager to contribute to new projects or repositories. Recently, I've been actively solving problems on LeetCode, and I believe sharing these solutions on your repository would be a valuable addition. I've taken a look at your README and I'm impressed by the project.

Could you please let me know if I can contribute? Thank you! 😊

**Comment by Soumya-0x000** [comment]
**Yes!** _It will be my pleasure _
